### ISSUE TITLE
objectAssign$1 is not a function

### ISSUE THREAD

**Issue by LightningVII** [yamafaktory/babel-react-rollup-starter#91]
objectAssign$1 is not a function

**Comment by yamafaktory** [comment]
Hi @LightningVII,

If you use the latest version of this project the error won't appear.

Current master is broken because of #90. I'm waiting for https://github.com/rollup/rollup-plugin-commonjs/issues/242 to be fixed (awaiting latest version to be published to npm).

**Comment by LightningVII** [comment]
OK, Thank you very much
